Calypso/ab19140 handle long messages (greater than 1 mb)
UKHO/EventHub-Logging-Provider pull request #29
Opened 2022-01-28 14:51 UTC by ioanGal

[This is a solution for the following story](https://dev.azure.com/ukhydro/Calypso/_workitems/edit/19140)

_**Details :**_ 

It is believed that message being sent to EventHub is too large and then getting rejected.

https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-faq#:~:text=The%20maximum%20message%20size%20allowed%20for%20Event%20Hubs%20is%201%20MB.

For example in the File Share Service when we cannot resolve the host, the Exception is logged in App insights but does not get sent to EventHub, instead the call to Eventhub shows as errored with little additional information supplied.

**_Investigation:_** 

Using the Dev environment 4  different messages were sent to event hub as errors and the results were:

 1.5 MB --> failed
 0.9 MB --> success
 0.5 MB --> success
 60 KB --> success
The messages can be found on azure log container and Kibana
A container was linked and set up temporary for the event hub blobs  during the investigation

The results show that the maximum message size is 1MB and if the message exceeds this limit then there is no exception from Azure event hub but the message is missing as well

**_Notes:_**

- The fileSHA(BlobContentInfo.EncryptionKeySha256) parameter is only active when the blob was encrypted with a customer-provided key [link](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobcontentinfo.encryptionkeysha256?view=azure-dotnet#azure-storage-blobs-models-blobcontentinfo-encryptionkeysha256)

- The operation supports cancellations(for future use).
 
- The following unit tests were introduced  ![image](https://user-images.githubusercontent.com/90547152/151566582-1cc78600-e722-43de-827a-baf56c01295e.png)

- The manual tests were executed using the Gatekeeper (locally) - EES

- There are 2 storing methods. An asynchronous and a synchronous. The provider uses the asynchronous.

2022-01-31 15:36 UTC, elerivaliant requested changes
Suggested change in behaviour may require some restructure

2022-01-31 15:36 UTC, elerivaliant commented on UKHO.Logging.EventHubLogProvider/EventHubLog.cs
> +                }
I would like to see this behave differently. At the moment it looks like you have to have set up the storage account config to even check whether you have large log messages. I would prefer that the check evaluates the size of the log  regardless, and if the config for the storage account isn't there, there's a static message which says something like "A log over 1MB was submitted with a message of {message template}. Please enable the Azure Storage Event Logging feature to store details of oversize logs." so that at least we get something in the logging to indicate that a large log has been seen regardless of whether the client provides any additional configuration.

2022-01-31 15:36 UTC, elerivaliant commented on UKHO.Logging.EventHubLogProvider/EventHubLoggerProvider.cs
> +                                                                 new EventHubLog(new EventHubClientWrapper(options.EventHubConnectionString, options.EventHubEntityPath,options.AzureStorageLogProvider
Is it still possible to call this without providing the log provider options at all, so if clients choose to upgrade to the new version they won't see any change in how they have to configure it?

2022-01-31 15:58 UTC, ioanGal commented on UKHO.Logging.EventHubLogProvider/EventHubLoggerProvider.cs
> +                                                                 new EventHubLog(new EventHubClientWrapper(options.EventHubConnectionString, options.EventHubEntityPath,options.AzureStorageLogProvider
@elerivaliant  We agreed to incorporate it as a configurable option. If the client doesn't pass the new options then code will still works just like before but without the new functionality enabled.

2022-01-31 16:02 UTC, ioanGal commented on UKHO.Logging.EventHubLogProvider/EventHubLog.cs
> +                }
ok, so in the case the message (as suggested above) will just be an indicator that the system captured an error that was >1mb but the details will be disposed. Ok we will update it then

2022-02-01 10:55 UTC, ioanGal commented on UKHO.Logging.EventHubLogProvider/EventHubLog.cs
> +                }
done

2022-02-01 10:57 UTC, ioanGal commented on UKHO.Logging.EventHubLogProviderTest/EventHubLoggerTests.cs
> +using System.IO;
There were 1-2 tests that were initially placed at EventHubLoggerTests to test while working. The reference is now removed.

2022-02-01 10:58 UTC, ioanGal commented on UKHO.Logging.EventHubLogProviderTest/Factories/ResourcesFactory.cs
> +        private static string GetSetting(string key)
It was used to read from a configuration file. The file was removed. The method is now removed as well.

2022-02-01 11:34 UTC, ioanGal commented on UKHO.Logging.EventHubLogProviderTest/Factories/AzureStorageLogProviderOptionsDummyFactory.cs
> +    public class AzureStorageLogProviderOptionsDummyFactory : DummyFactory<AzureStorageLogProviderOptions>
We though that a factory will  be a more maintainable solution because we can use it through FakeItEasy instead of creating new classes inline or setting them up for each of the test classes.

2022-02-01 11:46 UTC, ioanGal commented on UKHO.Logging.EventHubLogProvider/AzureStorageEventLogging/Interfaces/IAzureStorageEventLogger.cs
> +    public interface IAzureStorageEventLogger
I prefer having a contract  to act as a contract for future development. Additionally, this specific interface contains BlobContainerClient (Azure.Storage.Blobs) which has many dependencies (system buffers, json etc) . If you think that we should be following the Yagni principle for this one then we will remove it.

2022-02-04 09:20 UTC, devenma67 commented on UKHO.Logging.EventHubLogProviderTest/AzureStorageEventLoggerTests.cs
> +﻿using System;
@elerivaliant - El I have just downloaded the latest code and ran all the tests and all tests have passed successfully additionally the build and tests on the server have ran successfully as well shall we have a look into this once you free @ioanGal

2022-02-04 10:27 UTC, elerivaliant commented on UKHO.Logging.EventHubLogProvider/AzureStorageEventLogging/Enums/AzureStorageLoggingCheckResult.cs
> +        LoggingWithMessage = 2
Could we look at renaming these to be more reflective of what we're doing? We should always be logging something so it's more about are we just logging a warning or are we logging a warning and storing the log?

2022-02-04 10:27 UTC, elerivaliant commented on UKHO.Logging.EventHubLogProvider/AzureStorageEventLogging/Enums/AzureStorageEventLogCancellationResult.cs
> +        CancellationFailed = 2
What's the difference between unable to cancel and the cancellation failing?

2022-02-04 10:31 UTC, elerivaliant commented on UKHO.Logging.EventHubLogProviderTest/AzureStorageEventLoggerTests.cs
> +﻿using System;
If you're not seeing it then I'm possibly missing some local config or something I need to run those particular tests?
![image](https://user-images.githubusercontent.com/28015328/152513612-db62e465-eef4-4d81-886c-013964f7ecc2.png)
Given my calendar if @sajeelmunir or @Scawie can download it and don't see the same thing I'm happy to accept it's something weird on my machine, if it's that some local config needs to be done 'tis fine but we need to write it up on the docs.

2022-02-04 10:41 UTC, ioanGal commented on UKHO.Logging.EventHubLogProvider/AzureStorageEventLogging/Enums/AzureStorageLoggingCheckResult.cs
> +        LoggingWithMessage = 2
1) NoLogging --> Log Entry size  < 1M
2) NoLoggingWithMessageWarning --> The file is greater than 1mb but the azure storage logging option is disabled
3)LoggingWithMessage -->  The file is greater than 1mb and the azure storage logging option is disabled

We can add a description attribute with explanation if you want?

2022-02-04 10:43 UTC, ioanGal commented on UKHO.Logging.EventHubLogProvider/AzureStorageEventLogging/Enums/AzureStorageEventLogCancellationResult.cs
> +        CancellationFailed = 2
UnableToCancel  --> When the user asks for cancellation but it is not possible because it reached completion or a late operation stage

CancellationFailed  --> Exception during cancellations

This is an enum as well. We can add a description attribute with explanation if you want?

2022-02-04 10:44 UTC, ioanGal commented on UKHO.Logging.EventHubLogProviderTest/AzureStorageEventLoggerTests.cs
> +﻿using System;
Could you please have a look as mentioned by El above @sajeelmunir @Scawie ?

2022-02-04 10:47 UTC, elerivaliant commented on UKHO.Logging.EventHubLogProvider/AzureStorageEventLogging/Enums/AzureStorageEventLogCancellationResult.cs
> +        CancellationFailed = 2
Description would be good please

2022-02-04 10:55 UTC, elerivaliant commented on UKHO.Logging.EventHubLogProvider/AzureStorageEventLogging/Enums/AzureStorageLoggingCheckResult.cs
> +        LoggingWithMessage = 2
2 and 3 I still think need renaming here because 2 implies we're not logging when we are logging something, we're just not storing the original large log. Would we need a description attribute if we changed them to say 2 = LogWarningNoStorage and 3 = LogWarningAndStoreMessage because then I think they would be fairly self-explanatory?

2022-02-04 13:51 UTC, ioanGal commented on UKHO.Logging.EventHubLogProvider/AzureStorageEventLogging/Enums/AzureStorageLoggingCheckResult.cs
> +        LoggingWithMessage = 2
Oh ok I see. The intention was  nologging = no azure storage and messagewarning = message with the template informing the users that there was  a big message etc. Anyway, we will update

2022-02-04 14:40 UTC, ioanGal commented on UKHO.Logging.EventHubLogProvider/AzureStorageEventLogging/Enums/AzureStorageLoggingCheckResult.cs
> +        LoggingWithMessage = 2
@elerivaliant  done

2022-02-04 14:40 UTC, ioanGal commented on UKHO.Logging.EventHubLogProvider/AzureStorageEventLogging/Enums/AzureStorageEventLogCancellationResult.cs
> +        CancellationFailed = 2
@elerivaliant  done

2022-02-07 13:50 UTC, elerivaliant approved these changes

2022-02-08 16:40 UTC, merged